# Generated by Django 3.1.3 on 2021-04-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='статья')),
                ('parts', models.CharField(blank=True, max_length=10, null=True, verbose_name='часть')),
                ('code', models.CharField(choices=[('УК', 'Уголовный кодекс'), ('КоАП', 'Кодекс об административных правонарушениях')], default='УК', max_length=10, verbose_name='кодекс')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Дело')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('photo', models.ImageField(default='images/Noface.JPG', upload_to='images/cases')),
            ],
        ),
        migrations.CreateModel(
            name='Guilty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='гражданство')),
                ('organization', models.CharField(blank=True, max_length=150, null=True, verbose_name='организация')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='должность')),
                ('photo', models.ImageField(default='images/Noface.JPG', upload_to='images/Guilty')),
            ],
        ),
        migrations.CreateModel(
            name='Perseqution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата преследования')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='Окончание преследования')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.case')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='короткое название')),
                ('full_name', models.CharField(blank=True, max_length=250, verbose_name='полное название')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='адрес')),
            ],
        ),
        migrations.CreateModel(
            name='RestrictionOfVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=150, verbose_name='ограничения')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOfVictimInPers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPersecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='тип преследования')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(max_length=150, verbose_name='нарушение права')),
                ('content', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationInPersecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.perseqution')),
                ('rights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.violation')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, verbose_name='биография')),
                ('photo', models.ImageField(default='images/Noface.JPG', upload_to='images/victims')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbase.place')),
                ('restriction', models.ForeignKey(default='На свободе', on_delete=django.db.models.deletion.CASCADE, to='dbase.restrictionofvictim')),
            ],
        ),
        migrations.AddField(
            model_name='perseqution',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.statusofvictiminpers'),
        ),
        migrations.AddField(
            model_name='perseqution',
            name='type_of_pers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.typeofpersecution'),
        ),
        migrations.AddField(
            model_name='perseqution',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.victim'),
        ),
        migrations.CreateModel(
            name='GuiltyInPersecutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guilty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.guilty')),
                ('perseqution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.perseqution')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesInPersecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aricle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.article')),
                ('persecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbase.perseqution')),
            ],
        ),
    ]
