# Generated by Django 3.1.3 on 2021-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0002_auto_20210406_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilty',
            name='photo',
            field=models.ImageField(default='dbase/images/Noface.JPG', upload_to='images/Guilty'),
        ),
    ]
