# Generated by Django 3.1.3 on 2021-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0003_auto_20210406_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilty',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to='images/Guilty'),
        ),
    ]
