# Generated by Django 3.1.3 on 2021-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0004_auto_20210406_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to=''),
        ),
    ]
