# Generated by Django 3.1.3 on 2021-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0005_auto_20210406_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to='images'),
        ),
    ]
