# Generated by Django 3.1.3 on 2021-04-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0006_auto_20210406_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilty',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to='images/guilty'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to='images/victims'),
        ),
    ]
