# Generated by Django 3.1.3 on 2021-04-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0007_auto_20210406_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesinpersecution',
            old_name='aricle',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='case',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to='static/images/cases'),
        ),
        migrations.AlterField(
            model_name='guilty',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to='dbase/images/guilty'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='photo',
            field=models.ImageField(default='images/Noface.JPG', upload_to='dbase/images/victims'),
        ),
    ]
